#!/bin/sh
# make 3 blank 80-track double-sided double-density disk images

## now 2 disks.. _1.dsk is now my miscellaneous working stuff disk.

##os9 format -e -t80 -ds -dd nitros9_1.dsk -n"NitrOS-9/6809 Level 1 util disk1"
os9 format -e -t80 -ds -dd nitros9_2.dsk -n"NitrOS-9/6809 Level 1 util disk2"
os9 format -e -t80 -ds -dd nitros9_3.dsk -n"NitrOS-9/6809 Level 1 util disk3"

# create some stuff on each of them
##os9 makdir nitros9_1.dsk,CMDS
##os9 makdir nitros9_1.dsk,DSK1_INFO

os9 makdir nitros9_2.dsk,CMDS
os9 makdir nitros9_2.dsk,DSK2_INFO

os9 makdir nitros9_3.dsk,CMDS
os9 makdir nitros9_3.dsk,DSK3_INFO
